// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa1znh_U9JjP4vlPk4Fz6_3qsctV8MpY4',
    appId: '1:847399717440:android:5e9395ea54b9117438ada5',
    messagingSenderId: '847399717440',
    projectId: 'chat-23d66',
    storageBucket: 'chat-23d66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD7N1rC7rnO4OA5pRf3nQh5urjOMSEei8',
    appId: '1:847399717440:ios:26c4e63c23e72de938ada5',
    messagingSenderId: '847399717440',
    projectId: 'chat-23d66',
    storageBucket: 'chat-23d66.appspot.com',
    iosBundleId: 'com.example.whatsappUi',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8Vue3s6c-vya1ralsIrUMM0mjsQbGV-I',
    appId: '1:847399717440:web:c3441d1f093c293638ada5',
    messagingSenderId: '847399717440',
    projectId: 'chat-23d66',
    authDomain: 'chat-23d66.firebaseapp.com',
    storageBucket: 'chat-23d66.appspot.com',
    measurementId: 'G-F2S3488PBC',
  );

}